=== JuPedSim/jpsreport/xsd/jps_report.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
         <!-- XML Schema Generated from XML Document on Thu Dec 11 2014 15:35:09 GMT+0100 (CET) -->
         <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
         <xs:element name="JPSreport">
               <xs:complexType>
                     <xs:sequence>
                           <xs:element name="geometry">
                                 <xs:complexType>
                                       <xs:attribute name="file" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="trajectories">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="file">
                                                   <xs:complexType>
                                                         <xs:attribute name="name" type="xs:string"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="path">
                                                   <xs:complexType>
                                                         <xs:attribute name="location" type="xs:string"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="format" type="xs:string"></xs:attribute>
                                       <xs:attribute name="unit" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="measurementAreas">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="area_B">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="p1">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:double"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:double"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="p2">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:double"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:double"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="p3">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:double"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:double"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="p4">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:double"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:double"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="movingDirection">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="start" type="xs:string"></xs:attribute>
                                                                           <xs:attribute name="end" type="xs:string"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                         <xs:attribute name="type" type="xs:string"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="area_L">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="start">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:double"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:int"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="end">
                                                                     <xs:complexType>
                                                                           <xs:attribute name="x" type="xs:int"></xs:attribute>
                                                                           <xs:attribute name="y" type="xs:int"></xs:attribute>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                         <xs:attribute name="type" type="xs:string"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="unit" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="velocity">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="useXComponent" type="xs:string"></xs:element>
                                             <xs:element name="useYComponent" type="xs:string"></xs:element>
                                             <xs:element name="halfFrameNumberToUse" type="xs:int"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="method_A">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="timeInterval" type="xs:int">
                                                   <xs:complexType>
                                                         <xs:attribute name="unit" type="xs:string"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="measurementArea">
                                                   <xs:complexType>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="method_B">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="measurementArea">
                                                   <xs:complexType>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="method_C">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="measurementArea">
                                                   <xs:complexType>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="method_D">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="measurementArea">
                                                   <xs:complexType>
                                                         <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="cutByCircle">
                                                   <xs:complexType>
                                                         <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                                         <xs:attribute name="radius" type="xs:int"></xs:attribute>
                                                         <xs:attribute name="edges" type="xs:int"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="getProfile">
                                                   <xs:complexType>
                                                         <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                                         <xs:attribute name="scale_x" type="xs:double"></xs:attribute>
                                                         <xs:attribute name="scale_y" type="xs:double"></xs:attribute>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                       <xs:attribute name="enabled" type="xs:string"></xs:attribute>
                                       <xs:attribute name="outputGraph" type="xs:string"></xs:attribute>
                                       <xs:attribute name="individualFDdata" type="xs:string"></xs:attribute>
                                 </xs:complexType>
                           </xs:element>
                     </xs:sequence>
                     <xs:attribute name="project" type="xs:string"></xs:attribute>
                     <xs:attribute name="version" type="xs:double"></xs:attribute>
               </xs:complexType>
         </xs:element>
   </xs:schema>
 

=== JuPedSim/jpsreport/demos/T-Junction/ini_KO-240-050-240.xml
<?xml version="1.0" encoding="UTF-8" ?>

<JPSreport project="JPS-Project" version="0.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/0.6/jps_report.xsd">
	<!-- geometry file -->
	<geometry file = "./geometry_KO-240-050-240.xml" />
	<!-- trajectories file and format -->
	<!-- either a file name or a path location. In the latter case all files in the directory will be used-->
	<trajectories format="xml" unit="m">
		<file name="trajectory_KO-240-050-240.xml" />
		<!--<file name="U2_ptrkallord.xml" />
		<file name="l2.xml" /> -->
		<path location="./data/" />  
	</trajectories>
	<!-- all files in the directories will be used -->

	<measurementAreas unit="m">
		<area_B id="1" type="BoundingBox">
			<p1 x="-240" y="100" /> <!-- Clockwise -->
			<p2 x="-240" y="300" />
			<p3 x="0" y="300" />
			<p4 x="0" y="100" />
			<movingDirection start="p1" end="p2" />
		</area_B>
		<area_L id="2" type="Line">
			<start x="-240" y="100" />
			<end x="0" y="100" />
		</area_L>
	</measurementAreas>

	<velocity>
		<useXComponent>true</useXComponent>
		<useYComponent>true</useYComponent>

		<!-- half of the time interval that used to calculate instantaneous velocity 
			of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location. -->
		<halfFrameNumberToUse>5</halfFrameNumberToUse>
	</velocity>

	<!-- Method A (Zhang2011a) Flow and Vel -->
	<method_A enabled="true">
		<!-- Time interval used to count the flow [fr] -->
		<timeInterval unit="frame">
			100
		</timeInterval>
			<!-- The coordinate of the line used to calculate the flow and velocity -->
		<measurementArea id="2" />
	</method_A>

	<!-- Method B (Zhang2011a) Vel and Dens based on Tin and Tout -->
	<method_B enabled="true">
		<measurementArea id="1" />
	</method_B>

	<!-- Method C (Zhang2011a) Classical density and Vel -->
	<method_C enabled="true">
		<measurementArea id="1" />
	</method_C>

	<!-- Method D (Zhang2011a) Voronoi density and Vel -->
	<method_D enabled="true" cutByCircle="false" outputGraph="true"
		individualFDdata="true">
		<measurementArea id="1" />
		<getProfile enabled="false" scale_x="50" scale_y="50"/>

	</method_D>
</JPSreport>

=== JuPedSim/jpsreport/demos/obstacle/ini_crossing_90_c_6_v5.xml
<?xml version="1.0" encoding="UTF-8"?> 
<JPSreport project="JPS-Project" version="0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/jps_report.xsd"> 
    <!-- geometry file --> 
    <geometry file = "geo_crossing_90_c_6_v5.xml" /> 
    <!-- trajectories file and format --> 
    <!-- either a file name or a path location. In the latter case all files in the directory will be used--> 
    <trajectories format="txt" unit="m"> 
        <file name="traj_crossing_90_c_6_v5.txt" /> 
        <path location="./" /> 
    </trajectories> 
    <!-- all files in the directories will be used --> 

    <measurementAreas unit="m"> 
        <area_B id="1" type="BoundingBox"> 
            <vertex x="0.00" y="0.00" /> 
            <vertex x="0.00" y="4.00" /> 
            <vertex x="4.00" y="4.00" /> 
            <vertex x="4.00" y="0.00" /> 
            <Length_in_movement_direction distance="4.0" /> 
        </area_B> 
        <area_L id="2" type="Line"> 
            <start x="4" y="0" /> 
            <end x="4" y="4" /> 
        </area_L> 
    </measurementAreas> 

    <velocity> 
        <useXComponent>true</useXComponent> 
        <useYComponent>true</useYComponent> 
        <!-- half of the time interval that used to calculate instantaneous velocity of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location. --> 
        <halfFrameNumberToUse>5</halfFrameNumberToUse> 
    </velocity> 

    <!-- Method A (Zhang2011a) Flow and Vel --> 
    <method_A enabled="true"> 
        <!-- Time interval used to count the flow [fr] --> 
        <timeInterval unit="frame"> 
            100 
        </timeInterval> 
        <!-- The coordinate of the line used to calculate the flow and velocity --> 
        <measurementArea id="2" /> 
    </method_A> 

    <!-- Method B (Zhang2011a) Vel and Dens based on Tin and Tout --> 
    <method_B enabled="false"> 
        <measurementArea id="1" /> 
    </method_B> 

    <!-- Method C (Zhang2011a) Classical density and Vel --> 
    <method_C enabled="false"> 
        <measurementArea id="1" /> 
    </method_C> 

    <!-- Method D (Zhang2011a) Voronoi density and Vel --> 
    <method_D enabled="true" outputGraph="true" individualFDdata="false"> 
        <measurementArea id="1" /> 
        <cutByCircle enabled="false" radius= "1" edges = "10"/> 
        <!-- edges represent the precision of discretization of the circle ---> 
        <getProfile enabled="false" scale_x="0.20" scale_y="0.20"/> 
    </method_D> 

</JPSreport>
